### ISSUE TITLE
Dispense ETH as well

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-faucet#3]
**Is your feature request related to a problem? Please describe.**
Right now, the faucet can be used to dispense ERC20 tokens.
But for POA networks, we need to be able to dispense gas tokens as well.

**Describe the solution you'd like**
If token address is 0x0000000000000000000000000000000000000000 , then we will dispense ETH instead of ERC20
All the other flows will remain unchanged

**Comment by jamiehewitt15** [comment]
@alexcos20 Just checking I'm understanding this correctly: you want the faucet to dispense Eth if the token contract is set to 0x0000000000000000000000000000000000000000 in the .env? So in that case the faucet would only dispense Eth. The other option would be to set it up so that it can dispense both Eth and Ocean tokens.

**Comment by alexcos20** [comment]
Yes, only ETH.
